#!/usr/bin/python

import sys
from PySide.QtGui import QApplication
from neoman.view import mainwin

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = mainwin.MainWindow()
    window.show()

    sys.exit(app.exec_())
